/* ---------------------------------------------------------------------
 * Dades del mòdul "Mapa mut i Eixample" (prova pilot).
 * Transcrites del manual (Curs Online Credencial del Taxi 2026, Escola
 * del Taxi Incrementa), pàg. 127-138 i 164-165 (SEU-2 Eixample).
 * Fets (noms de carrers, adreces): no tenen drets d'autor. No incloure
 * aquí text redactat pel manual (preguntes, explicacions).
 * No editar a mà des de build.py; és un fitxer font més de src/.
 * ------------------------------------------------------------------- */
window.EIXAMPLE = {
  barris: ['la Nova Esquerra de l’Eixample', 'l’Antiga Esquerra de l’Eixample',
    'la Dreta de l’Eixample', 'la Sagrada Família', 'Sant Antoni', 'el Fort Pienc'],
  verticals: [
    { id: 'tarragona', name: 'Tarragona', order: 1, from: 'Pl. Espanya', to: 'Pl. Països Catalans', sentit: 'mar', notes: ['Doble sentit exclusiu Bus-Taxi', 'Continuació de Numància'] },
    { id: 'llanca', name: 'Llançà / Nicaragua', order: 2, from: 'Sepúlveda', to: 'Travessera de les Corts', notes: ['Nom canvia a Nicaragua passat Av. Roma', 'Tallat entre Diputació i Aragó pel Parc Miró'] },
    { id: 'vilamari', name: 'Vilamarí', order: 3, from: 'Av. Paral·lel', to: 'Provença', sentit: 'mar' },
    { id: 'entenca', name: 'Entença', order: 4, from: 'Av. Paral·lel', to: 'Diagonal', sentit: 'muntanya', notes: ['Continua com Dr. Fleming'] },
    { id: 'rocafort', name: 'Rocafort', order: 5, from: 'Av. Paral·lel', to: 'Av. Josep Tarradellas', sentit: 'mar' },
    { id: 'calabria', name: 'Calàbria', order: 6, from: 'Av. Paral·lel', to: 'Londres', sentit: 'muntanya' },
    { id: 'viladomat', name: 'Viladomat', order: 7, from: 'Av. Paral·lel', to: 'Av. Josep Tarradellas', sentit: 'mar' },
    { id: 'comteborrell', name: 'Comte Borrell', order: 8, from: 'Av. Paral·lel', to: 'Av. Josep Tarradellas', sentit: 'mar', notes: ['Peatonal entre Tamarit i Manso', 'Tallat entre Rosselló i París per l’Escola Industrial'] },
    { id: 'comteurgell', name: 'Comte Urgell', order: 9, from: 'Rda. St. Antoni', to: 'París', sentit: 'variable', notes: ['Continuació inferior: Rda. St. Pau'] },
    { id: 'villarroel', name: 'Villarroel', order: 10, from: 'Rda. St. Antoni', to: 'Diagonal', sentit: 'mar' },
    { id: 'casanova', name: 'Casanova', order: 11, from: 'Rda. St. Antoni', to: 'Travessera de Gràcia', sentit: 'muntanya' },
    { id: 'muntaner', name: 'Muntaner', order: 12, from: 'Rda. St. Antoni (Pl. Goya)', to: 'Pl. Bonanova', sentit: 'mar' },
    { id: 'aribau', name: 'Aribau', order: 13, from: 'Pl. Universitat', to: 'Via Augusta', sentit: 'muntanya' },
    { id: 'enricgranados', name: 'Enric Granados', order: 14, from: 'Diagonal', to: 'Diputació', sentit: 'mar', notes: ['Peatonal entre Diagonal-París i Consell de Cent-Diputació'] },
    { id: 'balmes', name: 'Balmes', order: 15, from: 'Pelai', to: 'Pl. John Kennedy / Pl. Molina', notes: ['Doble sentit entre Pl. Molina i Pl. John Kennedy'] },
    { id: 'ramblacatalunya', name: 'Rbla. Catalunya', order: 16, from: 'Pl. Catalunya', to: 'Diagonal', notes: ['Doble sentit'] },
    { id: 'pggracia', name: 'Pg. de Gràcia', order: 17, from: 'Pl. Catalunya', to: 'Pl. Nicolás Salmerón', notes: ['Doble sentit', 'Continua com Gran de Gràcia', 'Pl. Cinc d’Oros a la confluència amb Diagonal'] },
    { id: 'pauclaris', name: 'Pau Claris', order: 18, from: 'Pl. Urquinaona', to: 'Còrsega', sentit: 'mar' },
    { id: 'rogerlluria', name: 'Roger de Llúria', order: 19, from: 'Pl. Urquinaona', to: 'Còrsega', sentit: 'muntanya' },
    { id: 'bruc', name: 'Bruc', order: 20, from: 'Trafalgar', to: 'Còrsega', sentit: 'mar' },
    { id: 'girona', name: 'Girona', order: 21, from: 'Rda. St. Pere', to: 'Còrsega', sentit: 'muntanya', notes: ['Continuació inferior: Méndez Núñez'] },
    { id: 'bailen', name: 'Bailèn', order: 22, from: 'Rda. St. Pere', to: 'Trav. de Gràcia', sentit: 'mar' },
    { id: 'pgstjoan', name: 'Pg. St. Joan', order: 23, from: 'Rda. St. Pere', to: 'Trav. de Gràcia', notes: ['Doble sentit', 'Pl. Mn. Jacint Verdaguer amb Diagonal', 'Pl. Tetuán amb Gran Via'] },
    { id: 'rogerflor', name: 'Roger de Flor', order: 24, from: 'Pg. Pujades', to: 'Trav. de Gràcia', sentit: 'muntanya' },
    { id: 'napols', name: 'Nàpols', order: 25, from: 'Pg. Pujades', to: 'Trav. de Gràcia', sentit: 'mar' },
    { id: 'sicilia', name: 'Sicília', order: 26, from: 'Ali-Bei', to: 'Trav. de Gràcia', sentit: 'muntanya' },
    { id: 'sardenya', name: 'Sardenya', order: 27, from: 'Ramón Turró', to: 'Pl. Sanllehy', sentit: 'mar', notes: ['Continuació inferior: Ramón Trias Fargas'] },
    { id: 'marina', name: 'Marina', order: 28, from: 'Pl. Voluntaris Olímpics', to: 'Diputació', notes: ['Peatonal entre València i Provença'] },
    { id: 'lepant', name: 'Lepant', order: 29, from: 'Av. Meridiana', to: 'Rda. Guinardó', sentit: 'mar' },
    { id: 'padilla', name: 'Padilla', order: 30, from: 'Av. Meridiana', to: 'Rda. Guinardó', sentit: 'muntanya' },
    { id: 'castillejos', name: 'Castillejos', order: 31, from: 'Av. Meridiana', to: 'Av. Mare de Déu de Montserrat', notes: ['Tall per escales entre Rda. Guinardó i Niça (no es pot circular)'] },
    { id: 'cartagena', name: 'Cartagena', order: 32, from: 'Consell de Cent', to: 'Av. Mare de Déu de Montserrat', notes: ['Doble sentit entre Rda. Guinardó i Av. Mare de Déu de Montserrat'] },
    { id: 'dosdemaig', name: 'Dos de Maig', order: 33, from: 'Consell de Cent', to: 'St. Antoni Mª Claret', sentit: 'mar' },
  ],
  horizontals: [
    { id: 'granvia', name: 'Gran Via de les Corts Catalanes', order: 1, side: 'both' },
    { id: 'diputacio', name: 'Diputació', order: 2, side: 'both', notes: ['Tarragona↔Padilla sentit Llobregat'] },
    { id: 'consellcent', name: 'Consell de Cent', order: 3, side: 'both', notes: ['Creu Coberta↔Av. Meridiana'] },
    { id: 'arago', name: 'Aragó', order: 4, side: 'both', notes: ['Tarragona↔Lope de Vega / Av. Meridiana', 'Continua com Rbla. Guipúscoa'] },
    { id: 'valencia', name: 'València', order: 5, side: 'both', notes: ['Tarragona↔Espronceda', 'Continua com Huelva'] },
    { id: 'mallorca', name: 'Mallorca', order: 6, side: 'both', notes: ['Rector Triadó↔Clot', 'Absorbida per Av. Roma entre Tarragona i Rocafort'] },
    { id: 'provenca', name: 'Provença', order: 7, side: 'both', notes: ['Pl. Països Catalans↔Rogent/Independència'] },
    { id: 'rossello', name: 'Rosselló', order: 8, side: 'both', notes: ['Tallat pel Hospital Clínic (Villarroel-Casanova)', 'Peatonal entre Comte Urgell i Villarroel'] },
    { id: 'corsega', name: 'Còrsega', order: 9, side: 'both', notes: ['Av. Josep Tarradellas↔Pg. Maragall', 'Tallada per l’Escola Industrial', 'Peatonal entre Pg. Gràcia i Rbla. Catalunya'] },
    { id: 'buenosaires', name: 'Buenos Aires', order: 6.3, side: 'esquerra', from: 'Av. Sarrià', to: 'Comte Borrell' },
    { id: 'londres', name: 'Londres', order: 6.5, side: 'esquerra', from: 'Av. Josep Tarradellas', to: 'Aribau' },
    { id: 'paris', name: 'París', order: 6.7, side: 'esquerra', from: 'Av. Josep Tarradellas', to: 'Balmes' },
    { id: 'sepulveda', name: 'Sepúlveda', order: 1.5, side: 'esquerra' },
    { id: 'floridablanca', name: 'Floridablanca', order: 1.7, side: 'esquerra' },
    { id: 'tamarit', name: 'Tamarit', order: 1.8, side: 'esquerra' },
    { id: 'manso', name: 'Manso', order: 1.9, side: 'esquerra' },
    { id: 'parlament', name: 'Parlament', order: 1.95, side: 'esquerra' },
    { id: 'santantonimclaret', name: 'St. Antoni Mª Claret', order: 9.3, side: 'dreta' },
    { id: 'industria', name: 'Indústria', order: 9.4, side: 'dreta' },
    { id: 'casp', name: 'Casp', order: 2.3, side: 'dreta' },
    { id: 'ausiasmarc', name: 'Ausiàs Marc', order: 2.4, side: 'dreta' },
    { id: 'alibei', name: 'Ali Bei', order: 2.5, side: 'dreta' },
    { id: 'avvilanova', name: 'Av. Vilanova', order: 2.6, side: 'dreta' },
    { id: 'almogavers', name: 'Almogàvers', order: 2.7, side: 'dreta' },
    { id: 'travgracia', name: 'Travessera de Gràcia', order: 10, side: 'both', notes: ['Límit muntanya de l’Eixample'] },
  ],
  diagonals: [
    { id: 'avsarria', name: 'Av. Sarrià' }, { id: 'avroma', name: 'Av. Roma' },
    { id: 'avmistral', name: 'Av. Mistral' }, { id: 'avdiagonal', name: 'Av. Diagonal', notes: ['Travessa tot l’Eixample'] },
    { id: 'avgaudi', name: 'Av. Gaudí' }, { id: 'rdauniversitat', name: 'Rda. Universitat' },
    { id: 'rdastpere', name: 'Rda. St. Pere' }, { id: 'ribes', name: 'Ribes' }, { id: 'enamorats', name: 'Enamorats' },
  ],
};

window.EIXAMPLE_POIS = [
  { name: 'Sagrada Família', addr: 'Sardenya / Marina (Pl. Sagrada Família)', near: 'sardenya', cat: 'monument' },
  { name: 'Casa Amatller', addr: 'Pg. de Gràcia, 41', near: 'pggracia', cat: 'monument' },
  { name: 'Casa Batlló', addr: 'Pg. de Gràcia, 43', near: 'pggracia', cat: 'monument' },
  { name: 'Casa Lleó Morera', addr: 'Pg. de Gràcia, 35', near: 'pggracia', cat: 'monument' },
  { name: 'Casa Milà (La Pedrera)', addr: 'Pg. de Gràcia, 92', near: 'pggracia', cat: 'monument' },
  { name: 'Casa Terrades (de les Punxes)', addr: 'Diagonal, 416/420', near: 'bruc', cat: 'monument' },
  { name: 'Monument a Francesc Macià', addr: 'Pl. Catalunya', near: 'balmes', cat: 'monument' },
  { name: 'Monument a Rafael Casanova', addr: 'Rda. Sant Pere, 41', near: 'girona', cat: 'monument' },
  { name: 'Museu Egipci', addr: 'València, 284', near: 'pauclaris', cat: 'museu' },
  { name: 'Fundació Tàpies', addr: 'Aragó, 265', near: 'ramblacatalunya', cat: 'museu' },
  { name: 'Auditori de Barcelona', addr: 'Lepant, 150', near: 'lepant', cat: 'cultura' },
  { name: 'Conservatori Superior de Música', addr: 'Bruc, 110', near: 'bruc', cat: 'cultura' },
  { name: 'Hospital Clínic', addr: 'Villarroel, 170', near: 'villarroel', cat: 'hospital' },
  { name: 'Hospital Dos de Maig', addr: 'Dos de Maig, 301', near: 'dosdemaig', cat: 'hospital' },
  { name: 'Hospital de Nens de Barcelona', addr: 'Consell de Cent, 437', near: 'rogerflor', cat: 'hospital' },
  { name: 'Cinema Comèdia', addr: 'Pg. de Gràcia, 13', near: 'pggracia', cat: 'cinema' },
  { name: 'Hotel Majestic Barcelona', addr: 'Pg. de Gràcia, 68', near: 'pggracia', cat: 'hotel' },
  { name: 'Hotel Palace (antic Ritz)', addr: 'Gran Via, 668', near: 'rogerlluria', cat: 'hotel' },
  { name: 'Teatre Tívoli', addr: 'Casp, 8', near: 'pauclaris', cat: 'teatre' },
  { name: 'Teatre Nacional de Catalunya', addr: 'Pl. de les Arts', near: 'lepant', cat: 'teatre' },
  { name: 'Estació del Nord', addr: 'Ali Bei, 80', near: 'napols', cat: 'transport' },
  { name: 'El Corte Inglés Pl. Catalunya', addr: 'Pl. Catalunya, 14', near: 'balmes', cat: 'comerc' },
  { name: 'El Corte Inglés Francesc Macià', addr: 'Diagonal, 471', near: 'villarroel', cat: 'comerc' },
  { name: 'Escola Industrial', addr: 'Urgell, 187', near: 'comteurgell', cat: 'edifici' },
  { name: 'La Model (presó)', addr: 'Entença, 155', near: 'entenca', cat: 'edifici' },
  { name: 'Pl. de Toros Monumental', addr: 'Gran Via / Marina', near: 'marina', cat: 'edifici' },
  { name: 'Parc Joan Miró', addr: 'Tarragona / Aragó / Vilamarí / Diputació', near: 'tarragona', cat: 'parc' },
  { name: 'Casa Calvet', addr: 'Casp, 48', near: 'rogerlluria', cat: 'monument' },
  { name: 'Universitat de Barcelona', addr: 'Gran Via, 585', near: 'villarroel', cat: 'edifici' },
  { name: 'Monument a Dr. Robert', addr: 'Pl. Tetuán', near: 'pgstjoan', cat: 'monument' },
  { name: 'Hotel Mandarín Oriental', addr: 'Pg. de Gràcia, 38', near: 'pggracia', cat: 'hotel' },
  { name: 'Palau Macaya - CaixaForum', addr: 'Pg. de Sant Joan, 108', near: 'pgstjoan', cat: 'cultura' },
  { name: 'Mercat del Ninot', addr: 'Mallorca, 131-133', near: 'casanova', cat: 'mercat' },
  { name: 'Hospital Univ. Sagrat Cor', addr: 'Viladomat, 288', near: 'viladomat', cat: 'hospital' },
  { name: 'Mercat de Sant Antoni', addr: 'Urgell, 1', near: 'comteurgell', cat: 'mercat' },
];
